name: test

on: [pull_request]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    environment: TEST

    services:
      db_postgres:
        image: postgres:13
        ports:
          - 2345:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: notification-service-test

    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm ci

      - name: Create Test .env file
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_DATABASE_URL: postgresql://postgres:postgres@localhost:2345/notification-service-test?schema=public
          envkey_CRYPTR_SECRET: secret
          file_name: .env
          directory: .
          fail_on_empty: true

      - name: Run all tests
        run: npm run test
